### ISSUE TITLE
Crashes when starting the game

### ISSUE THREAD

**Issue by XxxXLuaLover** [Suleiman700/UCH-ModMenu#1]
The game crashes when i start it

**Comment by Suleiman700** [comment]
In order to solve this problem I need you to answer the question:

1. What operation system are you using?

2. What is the game version ?
Game version can be seen using:
in-game->options->video->show version

3. Which mod version you've used ?

4. Do you get any error message or any log file inside the game directory ?

@XxxXLuaLover

**Comment by XxxXLuaLover** [comment]
Windows 11

1.10.06

3.3

No

@Suleiman700

**Comment by XxxXLuaLover** [comment]
@Suleiman700 .

**Comment by Suleiman700** [comment]
After downloading and trying all versions it always crashes.

It seems like the mod version `1.9.03` does not work with the new game version `1.10.06` .

Unfortunately, I don't have enough time to patch it, :(

@XxxXLuaLover

**Comment by XxxXLuaLover** [comment]
Can you patch it when you have the time?

@Suleiman700

**Comment by Suleiman700** [comment]
> Can you patch it when you have the time?
> 
> @Suleiman700

Yes sure, I'll keep you updated.
@XxxXLuaLover

**Comment by RandomnamEmn** [comment]
its been 7 fucking months, are you done???

**Comment by RandomnamEmn** [comment]
WAKE THE FUCK UP

**Comment by Suleiman700** [comment]
Hello and thanks for contacting us.

Currently the ultimate chicken horse mod menu is private and costs $9.99.

If you are interested please let us know.

Have a great day.

**Comment by RandomnamEmn** [comment]
Bitch
